// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-vibes/GlassPastel.tsx": () => import("../components/mockups/dashboard-vibes/GlassPastel.tsx"),
  "./components/mockups/dashboard-vibes/WarmAnalog.tsx": () => import("../components/mockups/dashboard-vibes/WarmAnalog.tsx"),
  "./components/mockups/dashboard-vibes/ZenMonochrome.tsx": () => import("../components/mockups/dashboard-vibes/ZenMonochrome.tsx")
};
